### ISSUE TITLE
Compatibility of the distributable JavaScript

### ISSUE THREAD

**Issue by leodido** [paradox41/validate-commit#11]
The ["engines"](https://github.com/paradox41/validate-commit/blob/master/package.json#L37) field of package.json claims validate-commit require almost node 4.

Nevertheless the distributable contains JS features (i.e., default arguments) not available with node 4 (not even behind a flag). Infact default arguments landed in the new version of V8, that shipped w/ Node 6+.

I'm referring to the validateMessage generated methods.

```javascript
const validateMessage = function (message, options = {}) {}
                                                   ^
```

This results in error **SyntaxError: Unexpected token =**.

Some solutions:
1. Force your users to use node 6+ ( ... )
2. Change the tsconfig.json ["target"](https://github.com/paradox41/validate-commit/blob/master/tsconfig.json#L14) field back to ES5
3. Selectively force the compiler to translate default parameters into their ES5 corrispective (I do not know whether it is possible)

I would go with solution 2, if you agree.

**Comment by paradox41** [comment]
Agreed with 2. Didn't realize default args hadn't shipped until v6.

**Comment by paradox41** [comment]
Looking into it more, I guess [this](https://github.com/paradox41/validate-commit/blob/master/package.json#L44) is how all the tests were passing on node 4. I updated that value when I converted the `gulpfile` into TypeScript. Not sure why? I may have been testing things and it just got left that way.
