### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by paradox41** [paradox41/validate-commit#17]
We've added all the presets now, so the docs should show that.

**Comment by leodido** [comment]
WIP.

**Comment by paradox41** [comment]
Awesome! Could you give me a sense of how you are approaching it? Ideally
I'd like to have something like JSDOC that would automatically generate
markdown we could have in the repo. I am open to other suggestions though

**Comment by leodido** [comment]
For now I have in mind to just update the README.
For api docs rather we should adopt a solution similar/like that you just proposed.

**Comment by paradox41** [comment]
That sounds good. I think the pragmatic solution is updating the README (as it is very out of date just now).

We can look for good api docs tools once that gets done.

Feel free to ping me once you open the PR so I can take a look.

**Comment by leodido** [comment]
Readme upgraded @paradox41.

I also propose to change the name of the environment variable (i.e. CI) used to disable logging to something more intelligible like SILENT.

**Comment by paradox41** [comment]
@leodido awesome! Shall I expect a PR soon?

> change the name of the environment variable (i.e. CI) used to disable logging to something more intelligible like SILENT

Agreed

**Comment by leodido** [comment]
@paradox41 mute logging done ([51f014](https://github.com/paradox41/validate-commit/pull/19/commits/51f014f7fd71438c2864ae46570694d9f546acd0)).

Furthermore I improved code snippets within readme file.

I think we can merge #19. What do you think about?

**Comment by paradox41** [comment]
Closed via #19
