### ISSUE TITLE
Add support for other conventions

### ISSUE THREAD

**Issue by TomNeyland** [paradox41/validate-commit#2]
[What about these guys](https://github.com/paradox41/validate-commit/tree/master/conventions)

Conventions:

- [x] atom
- [x] ember
- [x] eslint
- [x] jquery
- [x] jshint

**Comment by paradox41** [comment]
Closed in [v2.2.0](https://github.com/paradox41/validate-commit/blob/master/CHANGELOG.md#220-2016-05-19)
