### ISSUE TITLE
mocha-sinon / mocha version conflict

### ISSUE THREAD

**Issue by ds82** [paradox41/validate-commit#34]
trying to `git clone` & `npm install` results in this:

```
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package mocha@3.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-sinon@1.1.5 wants mocha@>= 1.0.0 < 3.0.0
```

**Comment by paradox41** [comment]
What version of npm are you on?

**Comment by paradox41** [comment]
Should be fixed via https://github.com/elliotf/mocha-sinon/pull/11

**Comment by ds82** [comment]
Sorry for the late reply. I'm still have to use node 0.10, but your change fixed it indeed. Thanks!
